name: Deploy to XDN

on:
  push:
    branches:
      - commercial

jobs:
  deploy-to-xdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm-proxy.fury.io/moovweb/
      - run: npm ci
      - run: npm run deploy -- --branch=commercial --token=$xdn_deploy_token --environment=production
        env:
          xdn_deploy_token: ${{secrets.xdn_deploy_token}}
